# Generated by Django 4.0.3 on 2022-04-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
